# This Docker Compose file will spin up an ACS community installation on a local host.
# It requires at least 6GB of memory available to distribute among containers.
#
# For performance tuning, increase each container mem_limit and give a percentage of
# it to the JVM. Use either the -Xms,-Xmx flags or the newly added flags in
# java 10+: -XX:MaxRAMPercentage and -XX:MinRAMPercentage.
# More details here:
# https://www.oracle.com/technetwork/java/javase/10-relnote-issues-4108729.html
#
services:
  alfresco:
    #image: docker.io/alfresco/alfresco-content-repository-community:25.2.0
    image: docker.io/alfresco/alfresco-governance-repository-community:26.2.0
    mem_limit: 1900m
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dindex.subsystem.name=elasticsearch
        -Delasticsearch.createIndexIfNotExists=true
        -Delasticsearch.host=elasticsearch
        -Delasticsearch.port=9200
        -Dshare.host=localhost
        -Dshare.port=8080
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dcsrf.filter.enabled=false
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Dmessaging.broker.username=admin
        -Dmessaging.broker.password=admin
        -Ddeployment.method=DOCKER_COMPOSE
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-",
        ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 1m
    volumes:
      - ./data/services/content/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
      - ./data/services/content/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp
      - alf_data:/usr/local/tomcat/alf_data/
    extends:
      file: commons/base.yaml
      service: alfresco
  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:5.4.3
    #image: alfresco-tengine-pii
    mem_limit: 1536m
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/ready"]
      interval: 20s
      timeout: 2s
      retries: 3
      start_period: 10s
    depends_on:
      activemq:
        condition: service_healthy
  share:
    #image: docker.io/alfresco/alfresco-share:25.2.0
    image: docker.io/alfresco/alfresco-governance-share-community:26.2.0
    mem_limit: 1g
    environment:
      CSRF_FILTER_ORIGIN: http://localhost:8080
      CSRF_FILTER_REFERER: http://localhost:8080/share/.*
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/share"]
      interval: 20s
      timeout: 2s
      retries: 3
      start_period: 15s
    depends_on:
      alfresco:
        condition: service_healthy
    extends:
      file: commons/base.yaml
      service: share
  postgres:
    image: postgres:17.9
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - postgresdata:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:8.17.10
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  kibana:
    image: kibana:8.17.10
    mem_limit: 1g
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "curl", "-f", "-o", "/dev/null", "http://localhost:5601/status"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 30s
  batch-indexing:
    image: docker.io/alfresco/alfresco-elasticsearch-batch-indexing:5.7.0
    mem_limit: 1g
    depends_on:
      elasticsearch:
        condition: service_healthy
      alfresco:
        condition: service_healthy
      transform-core-aio:
        condition: service_healthy
    environment:
      JAVA_OPTS: "-Xms256m -Xmx768m"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alfresco
      SPRING_DATASOURCE_USERNAME: alfresco
      SPRING_DATASOURCE_PASSWORD: alfresco
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://transform-core-aio:8090/transform/config
      ALFRESCO_ACS_URL: http://alfresco:8080
      ALFRESCO_CONTENT_TRANSFORM_SHAREDSECRET: secret
      ALFRESCO_REINDEX_CONTINUOUS_POLLINGINTERVAL: 15s
      ALFRESCO_REINDEX_CONTINUOUS_CATCHUPPOLLINGINTERVAL: 1s
      ALFRESCO_REINDEX_CONTINUOUS_MAXWINDOW: 30m
      ALFRESCO_REINDEX_CONTINUOUS_OVERLAP: 10m
  activemq:
    image: docker.io/alfresco/alfresco-activemq:6.2.6-jre17-rockylinux8
    mem_limit: 1g
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    ports:
      - "8161:8161" # Web Console
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP
    healthcheck:
      test:
        [
          "CMD",
          "/opt/activemq/bin/activemq",
          "query",
          "--objname",
          "type=Broker,brokerName=*,service=Health",
          "|",
          "grep",
          "Good",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  content-app:
    image: alfresco/alfresco-content-app:8.0.0
    mem_limit: 128m
    environment:
      APP_BASE_SHARE_URL: "http://localhost:8080/aca/#/preview/s"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 1s
    extends:
      file: commons/base.yaml
      service: content-app
    profiles:
      - donotstart
  control-center:
    image: quay.io/alfresco/alfresco-control-center:11.0.0
    mem_limit: 128m
    environment:
      APP_CONFIG_PROVIDER: "ECM"
      APP_CONFIG_AUTH_TYPE: "BASIC"
      BASE_PATH: ./
    healthcheck:
      test: ["CMD", "curl", "-f", "http://alfresco:8080/"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 1s
    extends:
      file: commons/base.yaml
      service: control-center
    profiles:
      - donotstart
  proxy:
    extends:
      file: commons/base.yaml
      service: proxy
  ##########CUSTOM SERVICES BELOW##########
  # transform-pii:
  #   image: alfresco/transform-pii-redaction
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    #profiles:
    #  - donotstart

  open-webui:
    image: ghcr.io/open-webui/open-webui:main # Or :cuda for GPU support
    ports:
      - "3000:8080" # Host_port:Container_port
    volumes:
      #- ./data/services/openwebui:/app/backend/data # Persistent storage for Open WebUI data
      - ./data/services/openwebui/webui.db:/app/backend/data/webui.db # Persistent storage for Open WebUI data
      - openwebuidata:/app/backend/data # Persistent storage for Open WebUI data
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434 # Link to the Ollama service on the host
    profiles:
      - donotstart

  wildsalfmcp:
    image: wildsdocker/wildsalfmcp:v3
    ports:
      - 8000:8000
      - 8443:443
      - 8880:80
    environment:
      BASE_URL: "http://alfresco:8080"
      user: "admin"
      pass: "admin"
      FASTMCP_HOST: 0.0.0.0
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - donotstart
  ldap:
    image: bitnamilegacy/openldap:latest
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_PORT_NUMBER=389
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=com
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_USERS=demo
      - LDAP_PASSWORDS=demo
      - LDAP_PASSWORD_HASH={CLEARTEXT}
      - LDAP_CUSTOM_LDIF_DIR=/home
    volumes:
      #- ./data/services/bitnamildap:/bitnami/openldap
      - ldapdata:/bitnami/openldap
      - type: bind
        source: ./data/services/bitnamildap/init.ldif
        target: /home/init.ldif
  ldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - 6443:443
      - 8400:80
    #profiles:
    #  - donotstart
  email:
    #image: apache/james:memory-latest
    image: apache/james:demo-3.8.2
    ports:
      - 25:25
      - 465:465
      - 993:993
      - 143:143
      - 8500:8000
    volumes:
      #- ./data/services/email/domainlist.xml:/root/conf/domainlist.xml
      - ./data/services/email/initialdata.sh:/root/initialdata.sh
      - emaildata:/var/store
    profiles:
      - donotstart
  webmail:
    image: hardware/rainloop:latest
    volumes:
      - webmaildata:/rainloop/data
      - ./data/services/email/example.com.ini:/rainloop/data/_data_/_default_/domains/example.com.ini
    ports:
      - 8800:8888
    depends_on:
      - email
    profiles:
      - donotstart
volumes:
  alf_data:
  postgresdata:
  emaildata:
  webmaildata:
  ldapdata:
  openwebuidata:
